# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
name: OCI / Infra tools

on: # yamllint disable-line rule:truthy
  schedule:
  - cron: "00 01 * * 1"
  pull_request:
    paths:
    - .github/workflows/infra-tools.yaml
    - "images/infra-tools/*.yaml"
    - "images/infra-tools/**/*.yaml"
  push:
    branches:
    - "main"
    paths:
    - .github/workflows/infra-tools.yaml
    - "images/infra-tools/*.yaml"
    - "images/infra-tools/**/*.yaml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  security-events: write
  actions: read

jobs:
  publish:
    strategy:
      matrix:
        version: [latest]
        variant: [prod, shell, dev]
    name: ${{ matrix.version }}${{ matrix.variant == 'shell' && '-shell' || matrix.variant == 'dev' && '-dev' || '' }}
    uses: "./.github/workflows/release.yaml"
    with:
      repository: portefaix/infra-tools
      config-dir: images/infra-tools
      tag: ${{ matrix.version }}${{ matrix.variant == 'shell' && '-shell' || matrix.variant == 'dev' && '-dev' || '' }}
      target: ${{ matrix.variant }}
    secrets: inherit
